accounts/urls.py
from django.urls import include,path
from . import views

app_name='accounts'
urlpatterns = [
    
    path('signup',views.signup,name='signup'),
    path('profile',views.Profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    ]

book/urls.py
from django.urls import include,path
from . import views
from . import api
app_name='book'
urlpatterns = [
    
    path('',views.bookList,name='bookList'),
    path('add',views.addBook,name='addBook'),
    path('editBook/<str:slug>',views.editBook,name='editBook'),
    path('<str:slug>',views.bookDetails,name='book_details'),
    path('api/list',api.bookListApi,name='bookListApi'),
]

project/urls.py
from django import contrib
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('books/',include('book.urls',namespace='books')),
    path('home/',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('api-auth/',include('rest_framework.urls')),
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    nationalID=models.IntegerField(default=00000000000000)
    collageID=models.IntegerField(default=00000000)
    phoneNumber=models.CharField(max_length=13)
    city =models.ForeignKey('city',related_name='userCity',on_delete=models.CASCADE,blank=True,null=True)
    image=models.ImageField(upload_to='profile/')
    def __str__(self):
        return str(self.user)


@receiver (post_save, sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        profile.objects.create(user=instance)


class city(models.Model): 
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from .models import profile

class signUpForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model=profile
        fields=['nationalID','collageID','phoneNumber','city','image']

accounts/views.py
from typing import Reversible
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from .forms import signUpForm , UserForm,ProfileForm
from .models import profile
from django.urls.base import reverse
from django.db.models.query import QuerySet


def signup(request):
    if request.method=="POST":
        form=signUpForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form=signUpForm()
    return render(request,'registration/signup.html',{'form':form})


def Profile(request):
    Profile=profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':Profile})

def profile_edit(request):
    Profile=profile.objects.get(user=request.user)

    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileform=ProfileForm(request.POST,request.FILES,instance=Profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myProfileForm=profileform.save(commit=False)
            myProfileForm.user=request.user
            myProfileForm.save()
            return redirect(reverse('accounts:profile'))

    else:
        userform=UserForm(instance=request.user)
        profileform=ProfileForm(instance=Profile)
    return render(request,'accounts/edit_profile.html',{'userform':userform,'profileform':profileform})

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}{% load bootstrap4 %} {% load static %} {% block content %}



<h1 style="text-align:center;font-size:30px;color: #ff5f1b;">Edit Profile</h1><br>
<h1 style="text-align:center;font-size:25px;color: #ff5f1b;">Profile Detials</h1><br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form userform %}{% bootstrap_form profileform %} {% buttons %}
    <button type="submit" class="btn btn-primary">Save</button> {% endbuttons %}
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base0.html" %}{% load bootstrap4 %} {% load static %} {% block content %}
<!--end of nav -->
<div style="margin: 100px;background-color: #fff; opacity: 0.9; border: 0px;
        " class="row">
    <div class=" column">
        <a href="#" target="blank"><img style="width: 225px; height: 300px;" src="{{profile.image.url}}" alt=""></a>
        <br>

    </div>
    <div class="columnright">
        <h1 style="text-align: unset;">{{profile}}</h1>

        <br>
        <h3>Name: <span class="spann">{{profile}}</span> </h3>
        <h3>Email: <span class="spann">{{profile.user.email}}</span> </h3>
        <h3>Phone: <span class="spann">{{profile.phoneNumber}}</span> </h3>
        <h3>National ID: <span class="spann">{{profile.nationalID}}</span></h3>
        <br>
        <h3>Description:-</h3>
        <br>
        <p><span class="spann">{{book.description}}</span></p>

        <a class="borrowing" id="borrow" href="{% url 'accounts:profile_edit' %}" style="transform: translateX(-13%)translateY(18%);position:static;">Edit Profile</a>
    </div>

    {% endblock %}