accounts/urls.py
from django.urls import include,path
from . import views

app_name='accounts'
urlpatterns = [
    
    path('signup',views.signup,name='signup'),
    path('profile',views.Profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    ]

book/urls.py
from django.urls import include,path
from . import views
from . import api
app_name='book'
urlpatterns = [
    
    path('',views.bookList,name='bookList'),
    path('add',views.addBook,name='addBook'),
    path('editBook/<str:slug>',views.editBook,name='editBook'),
    path('<str:slug>',views.bookDetails,name='book_details'),
    path('api/list',api.bookListApi,name='bookListApi'),
]

home/urls.py
from django.urls.conf import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.homePage,name='homepage'),
    
    
    ]

project/urls.py
from django import contrib
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('books/',include('book.urls',namespace='books')),
    path('home/',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('api-auth/',include('rest_framework.urls')),
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'CSS/StyleSheet.css' %}" type="text/css" />

</head>

<body>

    <header>
        <div class="firstDiv">
            <ul>
                <li><a href="{% url 'home:homepage' %}">HOME</a></li>
                <li><a href="{% url 'books:bookList' %}">BOOKS</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">STUDENT-LOGIN</a></li>
                <li><a href="{% url 'login' %}">ADMIN-LOGIN</a></li>
                {% endif %}

                <li><a href="admin_login.html">Logout</a></li>
                <li><a href="#aboutus"><button id="button2">About us</button></a></li>
            </ul>
        </div>>

    </header>

    <div class="secondDiv">
        <div class="thirdDiv">
            <h1 style="text-align:center;font-size:35px;font-family: century Gothic;color: #ff5f1b;">University Library System</h1><br>
            <br> {% block content %} {% endblock content %}
        </div>
    </div>

    </div>

</body>


</html>

templates/base0.html
{% load bootstrap4 %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>book</title>
    <link rel="stylesheet" href="{% static 'CSS/styleBook.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="main">
        <section class="nav">
            <!-- start of nav-->
            <div style="position:fixed;" class="container">
                <ul>
                    <li><a href="{% url 'home:homepage' %}">HOME</a></li>
                    <li><a href="{% url 'books:bookList' %}">BOOKS</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">STUDENT-LOGIN</a></li>
                    <li><a href="{% url 'login' %}">ADMIN-LOGIN</a></li>
                    {% endif %}
                    <li><a href="admin_login.html">Logout</a></li>
                    <li><a href="#aboutus"><button id="button2">About us</button></a></li>
                </ul>
            </div>
            {% block content %} {% endblock content %}

</body>


</html>