book/urls.py
from django.urls import include,path
from . import views
from . import api
app_name='book'
urlpatterns = [
    
    path('',views.bookList,name='bookList'),
    path('add',views.addBook,name='addBook'),
    path('editBook/<str:slug>',views.editBook,name='editBook'),
    path('<str:slug>',views.bookDetails,name='book_details'),
    path('api/list',api.bookListApi,name='bookListApi'),
]

home/urls.py
from django.urls.conf import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.homePage,name='homepage'),
    
    
    ]

project/urls.py
from django import contrib
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('books/',include('book.urls',namespace='books')),
    path('home/',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('api-auth/',include('rest_framework.urls')),
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify



# Create your models here.
borrowingStatuChoices=(
    ('Available','Available'),
    ('Un available','Un available'),
)
class book(models.Model):
    owner=models.ForeignKey(User,related_name='bookOwner',on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    author=models.CharField(max_length=100)
    ISBN=models.IntegerField(default=0)
    numberOfPages=models.IntegerField(default=0)
    description=models.TextField()
    borrowingPeriod=models.IntegerField(default=0)
    borowingStatu=models.CharField(max_length=20,choices=borrowingStatuChoices)
    publishedAt=models.DateField(auto_now=True)
    image=models.ImageField(upload_to='books/')
    slug=models.SlugField(blank=True,null=True)

    def save (self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(book,self).save(*args,**kwargs)


    def __str__(self):
        return self.title

book/views.py
from typing import Reversible
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.utils.text import slugify
from .models import book
from django.core.paginator import Paginator
from .form import bookForm
from django.urls import reverse
from .filters import booktFilter
from django.contrib.auth.decorators import login_required
@login_required
def bookList(request):
    bookList=book.objects.all()

    myfilter=booktFilter(request.GET,queryset=bookList)
    bookList=myfilter.qs

    paginator=Paginator(bookList,1)
    page_number = request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    context={'bookList':page_obj,'myfilter':myfilter}
    return render(request,'book/bookList.html',context)

@login_required
def bookDetails(request,slug):
    bookDetails=book.objects.get(slug=slug)
    context={'book':bookDetails}
    return render(request,'book/bookDetails.html',context)

@login_required
def addBook(request):
    if request.method=='POST':
        form=bookForm(request.POST,request.FILES)
        if form.is_valid():
            print ('valid')
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            return redirect(reverse('books:bookList'))

    else :
        form=bookForm()


    return render(request,'book/addBook.html',{'form':form})
@login_required
def editBook(request,slug):
    editBook=book.objects.get(slug=slug)
    if (request.method=='POST'):
        form=bookForm(request.POST,instance=editBook)
        if form.is_valid:
            form.save()
        context={'book':editBook}
        return render(request,'book/bookDetails.html',context)
            
    else :
        form=bookForm(instance=editBook)
    return render(request,'book/editBook.html',{'form':form})

# Create your views here.

book/templates/book/addBook.html
{% extends "base.html" %}{% load bootstrap4 %} {% load static %} {% block content %}


<h1 style="text-align:center;font-size:30px;color: #ff5f1b;">Add New Book</h1><br>
<h1 style="text-align:center;font-size:25px;color: #ff5f1b;">Book Details</h1><br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">Add Now</button> {% endbuttons %}
</form>

{% endblock content %}

book/templates/book/adminHome.html
<!DOCTYPE html>
<html>

<head>
    <title>Admin Home Page</title>
    <link rel="stylesheet" href="{% static 'CSS/AdminHome.css' %}" type="text/css" />


    </style>
</head>

<body>
    <header>
        <div class="firstDiv">
            <ul>
                <li><a href="AdminHome.html">Home</a></li>
                <li><a href="UpdateBookDetails.html">Update Book Details</a></li>
                <li><a href="#">Contacts</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>

        <div class="secondDiv">
            <button class="btn"><a href="AddBook.html">Add Book</a></button>
            <button class="btn">View All Books</button>
        </div>

        </div>
    </header>
</body>


</html>

book/templates/book/admin_registeration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin registeration</title>
    <link rel="stylesheet" href="CSS/StyleSheet.css" type="text/css" />

</head>


<body>
    <header>
        <div class="firstDiv">
            <ul>
                <li><a href="Home.html">Home</a></li>
                <li><a href="AdminHome.html">Books</a></li>
                <li><a href="admin_registeration">Registration</a></li>
                <li><a href="#">Contacts</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>

        <div class="secondDiv">
            <div class="thirdDiv">
                <h1 style="text-align:center;font-size:35px;font-family: century Gothic;color: #ff5f1b;">University Library System</h1><br>
                <h1 style="text-align:center;font-size:25px;color: #ff5f1b;">Admin Login Page</h1><br>
                <form name="AddBook" action="" method="POST">
                    <input  type="text" name="FirstName" placeholder="First Name" required><br>
                    <input  type="text" name="LastName" placeholder="Last Name" required><br>
                    <input  type="Email" name="Email" placeholder="Email" required><br>
                    <input  type="Password" name="Password" placeholder="Password" required><br>
                    <button type="Sign" id="login">Sign Up</button>
                </form>
            </div>
        </div>
        
</div>
    </header>
</body>
<footer>
    <p class="pfooter">Email: <a href="Online.library@gmail.com">Online.library@gmail.com</a><p>
  </footer>
</html>

book/templates/book/bookDetails.html
{% extends "base0.html" %}{% load bootstrap4 %} {% load static %} {% block content %}


<!--end of nav -->
<div style="margin: 100px;background-color: #fff; opacity: 0.9; border: 0px;
        " class="row">
    <div class=" column">
        <a href="#" target="blank"><img style="width: 225px; height: 300px;" src="{{book.image.url}}" alt=""></a>
        <br>

    </div>
    <div class="columnright">
        <h1 style="text-align: unset;">{{book.title}}</h1>

        <br>
        <h3>Book Title: <span class="spann">{{book.title}}</span> </h3>
        <h3>Book ISBN: <span class="spann">{{book.ISBN}}</span> </h3>
        <h3>Book Author: <span class="spann">{{book.author}}</span> </h3>
        <h3>Published-At: <span class="spann">{{book.publishedAt|date:'d M o'}}</span></h3>
        <h3>Borrowing <span class="spann">{{book.borowingStatu}}</span></h3>
        <h3>Book Borrowing-Period: <span class="spann">{{book.borrowingPeriod}} Day's</span></h3>
        <br>
        <h3>Description:-</h3>
        <br>
        <p><span class="spann">{{book.description}}</span></p>

        <a class="borrowing" id="borrow" style="transform: translateX(-13%)translateY(18%);position:static;">Borrowing</a>
        <a class="borrowing" id="borrow" style="transform: translateX(-13%)translateY(18%);position:static;" href="{% url 'books:editBook' book.slug %}">Edit Book</a>
    </div>
    {% endblock content %}

book/templates/book/bookList.html
{% load bootstrap4 %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>book</title>
    <link rel="stylesheet" href="{% static 'CSS/styleBook.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="main">
        <section class="nav">
            <!-- start of nav-->
            <div style="position:fixed;" class="container">
                <ul>
                    <li><a href="{% url 'home:homepage' %}">HOME</a></li>
                    <li><a href="{% url 'books:bookList' %}">BOOKS</a></li>
                    <li><a href="updatedetail.html">Edit_profile</a></li>
                    <li><a href="#">Feedback</a></li>
                    <li><a href="{home.html}" onclick="confirm1()">Logout</a></li>
                </ul>
            </div>
        </section>
        <!--end of nav -->

        <!--start of header-->
        <section class="header">
            <div class="content">
                <h1 style="color:mediumspringgreen;">University Library System</h1>

            </div>
            <!-- content -->

            <!-- content -->
        </section>
        <!--end of header -->

        <section id="work" class="ourworks margin">
            <h2 style="color:aquamarine;">Books</h2>
            <div class="search-container">

                <!-- showlist  -->
                <div class="showlist">
                    <form class="form-style-5" method="GET">
                        {% bootstrap_form myfilter.form %}
                        <input type="submit" value="Search">

                    </form>
                </div>
            </div>
    </div>
    <div>
        {% for book in bookList %}

        <div class="polaroid">
            <a href="{% url 'books:book_details' book.slug %}" target="blank"><img src="{{book.image.url}}" alt="" style="width:20%;position: relative;
            left: 40%;margin-top: 50px;"></a>
            <div class="container1">
                <h2>{{book.title}}</h2>
                <a class="bookLink" href="{% url 'books:book_details' book.slug %}">More Info</a>
            </div>
        </div>


        {% endfor %}
    </div>
    {% if bookList.has_other_pages %}
    <div class="pagination_Bar" style="position: static;
    left: 49.25%;
    top: 169%;
    -webkit-transform: translate(-50%, -50%);
    transform: translate(-37%, -50%);
    margin: 97px;
    padding: 33px;
    border-radius: 60px;
    background-color: transparent;
    box-shadow: none;">
        <ul>
            {% if bookList.has_previous %}
            <li>
                <a style="color: white;" href="?page={{bookList.previous_page_number}}"> &laquo </a>
            </li>
            {% endif %} {% for i in bookList.paginator.page_range %} {% if i|divisibleby:5 %}
            <br> {% endif %}
            <li><a style="color: white;" href="?page={{i}}"><span>{{i}}</span></a></li>

            {% endfor %} {% if bookList.has_next %}
            <li>
                <a style="color: white;" href="?page={{bookList.next_page_number}}"> &raquo </a>
            </li>
            {% endif %}

        </ul>

        {% endif %}
    </div>
    <br>
    <!--end of pictures1-->

    </section>
    <!--end of ourworks-->
    <!-- review Book -->


    <!-- left-side col-5 -->
</body>


</html>

book/templates/book/editBook.html
{% extends "base.html" %} {% load bootstrap4 %}

<head>
    <title>Edit Book</title>
</head> {% block content %}



<h1 style="text-align:center;font-size:30px;color: #ff5f1b;">Edit Book</h1><br>
<h1 style="text-align:center;font-size:25px;color: #ff5f1b;">Book Details</h1><br>
<form method="POST">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">Change Now</button> {% endbuttons %}
</form>


{% endblock %}

book/templates/book/student_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>student login</title>
    <link rel="stylesheet" href="CSS/Student.css" type="text/css" />
    <script>
        function al() {
            alert("log in first")
        }
    </script>
<body>
    <header>
        <div class="firstDiv">
            <ul>
                <li><a href="Home.html">Home</a></li>
                <li><a href="AdminHome.html">Books</a></li>
                <li><a href="admin_registeration">Registration</a></li>
                <li><a href="#">Contacts</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>

        <div class="secondDiv">
            <div class="thirdDiv">
                <h1 style="text-align:center;font-size:35px;font-family: century Gothic;color: #000;">University Library System</h1><br>
                <h1 style="text-align:center;font-size:25px;color: #000;">Student Login Page</h1><br>
                <form class="add" name="AddBook" action="" method="POST">
                    <input class="Name" type="text" name="UserName" placeholder="User Name" required><br>
                    <input class="Password" type="Password" name="Password" placeholder="Password" required><br>
                    <button type="login" id="login">Login</button>
                </form>
            </div>
        </div>
        
</div>
    </header>
</body>
<footer>
    <p class="pfooter">Email: <a href="Online.library@gmail.com">Online.library@gmail.com</a><p>
</footer>
</html>

book/templates/book/student_registeration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>student registeration</title>
    <link rel="stylesheet" href="CSS/student.css" type="text/css" />

</head>

<body>
    <header>
        <div class="firstDiv">
            <ul>
                <li><a href="Home.html">Home</a></li>
                <li><a href="AdminHome.html">Books</a></li>
                <li><a href="admin_registeration">Registration</a></li>
                <li><a href="#">Contacts</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>

        <div class="secondDiv">
            <div class="thirdDiv">
                <h1 style="text-align:center;font-size:35px;font-family: century Gothic;color: #000;">University Library System</h1><br>
                <h1 style="text-align:center;font-size:25px;color: #000;">Admin Login Page</h1><br>
                <form name="AddBook" action="" method="POST">
                    <input  type="text" name="FirstName" placeholder="First Name" required><br>
                    <input  type="text" name="LastName" placeholder="Last Name" required><br>
                    <input  type="Email" name="Email" placeholder="Email" required><br>
                    <input  type="Password" name="Password" placeholder="Password" required><br>
                    <button type="Sign" id="login">Sign Up</button>
                </form>
            </div>
        </div>
        
</div>
    </header>
</body>
<footer>
    <p class="pfooter">Email: <a href="Online.library@gmail.com">Online.library@gmail.com</a><p>
  </footer>
</html>